name: Static code analysis

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: stable
            - uses: golangci/golangci-lint-action@v6
              with:
                  version: latest

    staticcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dominikh/staticcheck-action@v1.3.1
